name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: sudo /usr/share/rust/.cargo/bin/cargo build --verbose
    - name: Run tests
      run: sudo /usr/share/rust/.cargo/bin/cargo test --verbose
